apiVersion: 1

datasources:
  - name: QuestDB
    type: questdb-questdb-datasource
    access: proxy
    url: http://localhost:9000
    isDefault: true
    jsonData:
      httpMode: http
    editable: true
    version: 1
